Various imprvements for AC300 & AC500
Patrick762/hassio-bluetti-bt pull request #118
Opened 2024-06-29 13:53 UTC by AChep

Recently got AC500 and has been experiencing [no battery packs issue](https://github.com/Patrick762/hassio-bluetti-bt/issues/109) and frequent Unavailable statuses. Spent a few hours debugging and improving stuff:
- added BMS / ARM / DSP versions;
- fixed an issue with the component failing to read >1 battery pack;
- fixed a crash if sensor is unavailable right from the start;
- wrote a simple script that creates polling ranges from fields -- yay, no need to do that manually! It also has some tolerance, because sending tons of commands takes time and the time is valuable;
- changed max packs number of AC500 to 6;
- increased polling timeout and interval to compensate for a possible 6 battery packs handling.

2024-06-30 12:52 UTC, Patrick762 reviewed
Looks good so far, I'll test it on my EB3A and AC300 before merging

2024-06-30 12:52 UTC, Patrick762 commented on custom_components/bluetti_bt/bluetti_bt_lib/base_devices/ProtocolV1Device.py
> +        self.struct.add_version_field('dsp_version', 25)
I'll try this with my EB3A, if it fails we just add it to the device itself

2024-06-30 13:12 UTC, Patrick762 commented
Can you please rebase your branch?

2024-06-30 14:13 UTC, AChep commented
@Patrick762 I merged the changes in the upstream to my branch

2024-07-26 18:26 UTC, Patrick762 requested changes

2024-07-26 18:26 UTC, Patrick762 commented on custom_components/bluetti_bt/bluetti_bt_lib/base_devices/ProtocolV1Device.py
> +        self.struct.add_version_field('dsp_version', 25)
Works on EB3A

2024-07-26 18:26 UTC, Patrick762 commented on custom_components/bluetti_bt/bluetti_bt_lib/field_attributes.py
> +    ),
Should be added to diagnostics, see const.py DIAGNOSTIC_FIELDS

2024-07-26 18:26 UTC, Patrick762 commented
just a small change, then we can merge

2024-07-26 18:41 UTC, Patrick762 commented on custom_components/bluetti_bt/bluetti_bt_lib/bluetooth/device_reader.py
> +        _LOGGER.info("Pooling comands: " + ",".join([f"{c.starting_address}-{c.starting_address + c.quantity - 1}" for c in polling_commands]))
```suggestion
        _LOGGER.info("Polling commands: " + ",".join([f"{c.starting_address}-{c.starting_address + c.quantity - 1}" for c in polling_commands]))
```

2024-07-26 18:41 UTC, Patrick762 commented on custom_components/bluetti_bt/bluetti_bt_lib/devices/ac200m.py
> -            ReadHoldingRegisters(92, 1),
Sometimes I wonder why those registers were in the wrong place ...

2024-08-03 18:37 UTC, AChep commented
Took me a while, but I resolved those :)

2024-08-04 10:06 UTC, Patrick762 approved these changes

2024-08-04 10:07 UTC, merged