Additional EP600 values
Patrick762/hassio-bluetti-bt pull request #96
Opened 2024-04-22 11:36 UTC by KM011092

EP600 additions:
- Consumption values
- Grid, Consumptions and Solar Totals (as displayed on the first page of the Bluetti APP)

2024-04-27 10:02 UTC, Patrick762 commented
Could you remove the IntelliJ directory?

2024-04-28 07:40 UTC, KM011092 commented
> Could you remove the IntelliJ directory?
Not sure if I understand what you want me to remove. I am not aware that I‘ve added an IntelliJ directory. Can you please be a little more specific about what you want me to remove ?

2024-04-28 09:36 UTC, Patrick762 commented
I mean the .idea directory

2024-04-28 09:39 UTC, Patrick762 requested changes

2024-04-28 09:39 UTC, Patrick762 commented on .idea/.gitignore
> +# Default ignored files
Please remove this file

2024-04-28 09:39 UTC, Patrick762 commented on .idea/hassio-bluetti-bt-KM1.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file

2024-04-28 09:39 UTC, Patrick762 commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
Please remove this file

2024-04-28 09:39 UTC, Patrick762 commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file

2024-04-28 09:39 UTC, Patrick762 commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file

2024-04-28 09:39 UTC, Patrick762 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please remove this file

2024-04-28 15:32 UTC, Patrick762 approved these changes

2024-04-28 15:33 UTC, merged